//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictaFoule.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id_log { get; set; }
        public int id_log_level { get; set; }
        public string type { get; set; }
        public int id_project { get; set; }
        public string message { get; set; }
        public System.DateTime creation_date { get; set; }
    }
}
