//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictaFoule.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id_payment { get; set; }
        public string id_stripe { get; set; }
        public int amount { get; set; }
        public int id_project { get; set; }
        public string email { get; set; }
        public string name_customer { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual project project { get; set; }
    }
}
