//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictaFoule.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id_payment { get; set; }
        public string id_stripe { get; set; }
        public int amount { get; set; }
        public int id_project { get; set; }
        public string email { get; set; }
        public string name_customer { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual project project { get; set; }
    }
}
