//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictaFoule.Common.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sound_line
    {
        public int id_sound_line { get; set; }
        public int id_project { get; set; }
        public string sound_file_name { get; set; }
        public string sound_file_uri { get; set; }
        public string sound_file_transcript { get; set; }
        public System.DateTime creation_date { get; set; }
        public int state { get; set; }
        public Nullable<int> id_taskline { get; set; }
        public string task_answer { get; set; }
    
        public virtual project project { get; set; }
    }
}
